# -*- coding: utf-8 -*-
"""Dec9.inpyb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DAPRnWb3tNoG5qGFYVutwmRTC1MdPGat

## Dec 9 2023:  Extrapolate sequences
"""

def next_in_sequence(seq):
  diffs = []
  nextseq = seq
  while True:
    nextseq = np.diff(nextseq,1)
    diffs.append(nextseq)
    #print(diffs)
    if np.all(nextseq==0):
      break

  last = diffs[-1][-1]
  for cnt in range(len(diffs)-2,-1,-1):
    last = diffs[cnt][-1] + last
    #print(last)

  return(seq[-1]+last)

import numpy as np
# import pandas as pd

with open('Dec9.txt','r') as f:
  lines = f.readlines()

next_vals = []
for line in lines:
  temp = line.split()
  cur_sequence = [ int(val) for val in temp]
  next_vals.append(next_in_sequence(cur_sequence))

print(f'Part1: {np.sum(next_vals)}')

"""## Part 2
Extrapolate backwards
"""

def first_in_sequence(seq):
  diffs = []
  nextseq = seq
  while True:
    nextseq = np.diff(nextseq,1)
    diffs.append(nextseq)
    #print(diffs)
    if np.all(nextseq==0):
      break

  #print(diffs)
  prev_first = diffs[-1][0]
  for cnt in range(len(diffs)-2,-1,-1):
    prev_first = diffs[cnt][0] - prev_first
    #print(prev_first)

  return(seq[0]-prev_first)

import numpy as np
# import pandas as pd

with open('Dec9.txt','r') as f:
  lines = f.readlines()

prev_vals = []
for line in lines:
  temp = line.split()
  cur_sequence = [ int(val) for val in temp]
  prev_vals.append(first_in_sequence(cur_sequence))

print(f'Part 2:{np.sum(prev_vals)}')

first_in_sequence([0,3,6,9,12])

first_in_sequence([1,   3,   6,  10,  15,  21])

first_in_sequence([10 , 13,  16,  21,  30,  45 ])

