# -*- coding: utf-8 -*-
"""Dec6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aqSbe9o7-NsMFkigSXpGNrhTeMWK595I
"""

import numpy as np

#########
# Part 1
#########
Time=  [47,     70,     75,     66]
RecordDistance= [282,   1079 ,  1147,   1062]

numRecords = [0,0,0,0]
for competition in range(4):
  for holdTime in range(Time[competition]+1):
    speed = holdTime
    distance = (Time[competition]-holdTime)*speed
    if distance > RecordDistance[competition]:
      numRecords[competition]+=1

part1 = numRecords[0]*numRecords[1]*numRecords[2]*numRecords[3]

print(f'Part 1: {part1}')

##############
# Part 2
##############
Time = 47707566
RecordDistance = 282107911471062

numRecords = 0
for holdTime in range(14,Time+1-14):
  speed = holdTime
  distance = (Time-holdTime)*speed
  if distance > RecordDistance:
    numRecords+=1

print(f'Part2: {numRecords}')

